permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 作者信息
author: 
  name: 胡斌
  email: hubinary@163.com
  link: http://hubinary.com
  github: http://github.com/hubinary

# 站点信息
title: HuBinary
description: 胡斌的博客
url: http://hubinary.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xikhf.com1.z0.glb.clouddn.com/horse.jpg?imageView2/1/w/200/h/200/q/100/format/PNG
favicon: http://7xikhf.com1.z0.glb.clouddn.com/horse.jpg?imageView2/1/w/20/h/20/q/100/format/PNG

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: hubinary.com

# disqus 设置
disqus:
  shortname: hubinary
